sonar.organization=jbcjorge
sonar.projectKey=jbcjorge_mcp-ox

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=reports/coverage.out
sonar.go.tests.reportPaths=reports/junit.xml
